#!/bin/bash

echo "🚀 HealthX Deployment Guide"
echo "=============================="
echo ""

echo "📋 MANUAL DEPLOYMENT STEPS:"
echo ""
echo "1. BACKEND DEPLOYMENT (Railway):"
echo "   • Go to https://railway.app/"
echo "   • Sign up/Login with GitHub"
echo "   • Click 'New Project' → 'Deploy from GitHub repo'"
echo "   • Select this repository"
echo "   • Railway will auto-detect the project"
echo "   • Add environment variables:"
echo "     - MONGO_URL: mongodb+srv://[username]:[password]@cluster.mongodb.net/healthx"
echo "     - DB_NAME: healthx"
echo "     - PORT: 8001"
echo "   • Deploy and get the backend URL"
echo ""

echo "2. FRONTEND DEPLOYMENT (Vercel):"
echo "   • Go to https://vercel.com/"
echo "   • Sign up/Login with GitHub"
echo "   • Click 'New Project' → Import this repository"
echo "   • Set root directory to: frontend"
echo "   • Add environment variable:"
echo "     - REACT_APP_BACKEND_URL: [YOUR_RAILWAY_BACKEND_URL]"
echo "   • Deploy and get the frontend URL"
echo ""

echo "3. DATABASE SETUP (MongoDB Atlas):"
echo "   • Go to https://cloud.mongodb.com/"
echo "   • Create free cluster"
echo "   • Create database user"
echo "   • Whitelist all IPs (0.0.0.0/0)"
echo "   • Get connection string"
echo ""

echo "📁 PROJECT STRUCTURE:"
echo "   /app"
echo "   ├── backend/          # FastAPI backend"
echo "   ├── frontend/         # React frontend"
echo "   ├── Procfile          # Railway deployment"
echo "   ├── railway.json      # Railway config"
echo "   └── deploy.sh         # This guide"
echo ""

echo "🔧 LOCAL TESTING:"
echo "   Backend: cd backend && python server.py"
echo "   Frontend: cd frontend && yarn start"
echo ""

echo "✅ DEPLOYMENT CHECKLIST:"
echo "   □ MongoDB Atlas cluster created"
echo "   □ Backend deployed on Railway"
echo "   □ Frontend deployed on Vercel"
echo "   □ Environment variables configured"
echo "   □ Website accessible via Vercel URL"
echo ""

echo "🌐 FEATURES INCLUDED:"
echo "   ✅ HealthX main landing page"
echo "   ✅ User registration & login"
echo "   ✅ Presale page with crypto payments"
echo "   ✅ User dashboard"
echo "   ✅ Admin panel (/admin-secret-dashboard)"
echo "   ✅ Multi-crypto support (BTC, ETH, BNB)"
echo "   ✅ Responsive design"
echo ""

echo "📞 ADMIN ACCESS:"
echo "   URL: [YOUR_VERCEL_URL]/admin-secret-dashboard"
echo "   Username: Raihan081"
echo "   Password: Chowdhury1"
echo ""

echo "💰 CRYPTO ADDRESSES:"
echo "   ETH/BNB: 0x6d17BBD5De076A5837A537caE1Ae49B07575427E"
echo "   BTC: bc1qf3gq85j3fpd5wvqjmzyeqw2auvg2uelvwg9v24"