#!/bin/bash

# HealthX Deployment Quick Reference
# ==================================

echo "🚀 HealthX Quick Deployment Reference"
echo "====================================="
echo ""

echo "📋 DEPLOYMENT ORDER:"
echo "1. GitHub Repository ✅"
echo "2. MongoDB Atlas Database"
echo "3. Railway Backend"
echo "4. Vercel Frontend"
echo "5. Custom Domain (Optional)"
echo ""

echo "🔗 IMPORTANT LINKS:"
echo "MongoDB Atlas: https://cloud.mongodb.com/"
echo "Railway: https://railway.app/"
echo "Vercel: https://vercel.com/"
echo "Domain Registrar: https://namecheap.com/"
echo ""

echo "📝 VARIABLES TO COLLECT:"
echo ""
echo "From MongoDB Atlas:"
echo "└── Connection String: mongodb+srv://username:password@cluster.mongodb.net/"
echo ""
echo "From Railway:"
echo "└── Backend URL: https://your-project.up.railway.app"
echo ""
echo "From Vercel:"
echo "└── Frontend URL: https://your-project.vercel.app"
echo ""

echo "🎯 ENVIRONMENT VARIABLES:"
echo ""
echo "Railway (Backend):"
echo "├── MONGO_URL: [MongoDB connection string]"
echo "├── DB_NAME: healthx"
echo "├── SECRET_KEY: healthx-secret-key-2024-production"
echo "└── PORT: 8001"
echo ""
echo "Vercel (Frontend):"
echo "└── REACT_APP_BACKEND_URL: [Railway backend URL]"
echo ""

echo "💰 PAYMENT ADDRESSES (Already Configured):"
echo "├── ETH/BNB: 0x6d17BBD5De076A5837A537caE1Ae49B07575427E"
echo "└── BTC: bc1qf3gq85j3fpd5wvqjmzyeqw2auvg2uelvwg9v24"
echo ""

echo "🔐 ADMIN ACCESS (Already Configured):"
echo "├── URL: [your-website]/admin-secret-dashboard"
echo "├── Username: Raihan081"
echo "└── Password: Chowdhury1"
echo ""

echo "✅ TESTING CHECKLIST:"
echo "□ Home page loads with HealthX content"
echo "□ User registration/login works"
echo "□ Presale page shows crypto addresses"
echo "□ Dashboard displays after login"
echo "□ Admin panel accessible with credentials"
echo "□ Mobile responsive design"
echo "□ All API endpoints responding"
echo ""

echo "🚨 QUICK TROUBLESHOOTING:"
echo "Backend not starting? → Check Railway logs and environment variables"
echo "Frontend build failed? → Ensure root directory set to 'frontend'"
echo "Database connection failed? → Verify MongoDB connection string"
echo "API calls failing? → Check REACT_APP_BACKEND_URL in Vercel"
echo ""

echo "📖 For detailed instructions, read: DEPLOYMENT_GUIDE.md"
echo "⏱️  Total deployment time: 30-45 minutes"
echo "💸 Total cost: Free (or $12/year for custom domain)"